### ISSUE TITLE
win10下双击报错

### ISSUE THREAD

**Issue by klzw2233** [hzhilong/bilibili-backup#1]
![image](https://github.com/user-attachments/assets/04ddcad5-9db4-4807-8a22-87862cef1137)

**Comment by klzw2233** [comment]
![image](https://github.com/user-attachments/assets/21b40679-4201-4284-bff4-dcb5978748fe)

**Comment by hzhilong** [comment]
已修复执行路径存在空格的问题。麻烦下载一下新版本。 [bilibili-backup-1.0.1](https://github.com/hzhilong/bilibili-backup/releases/tag/v1.0.1)
