### ISSUE TITLE
还原过程中遇到被和谐账号会跳过

### ISSUE THREAD

**Issue by MisakaMikoto19090** [hzhilong/bilibili-backup#6]
版本:	2.0.3, 2.0.4
被和谐账号:	马督工, 当前情况是账号存在,但是无法关注.
又找到一个新的被和谐账号: 付鹏的财经世界

账号A关注包含马督工, 并生成备份.

账号B还原账号A的关注数据,遇到马督工, 会跳过剩余的关注数据, 进入稍后再看

当前解决方案, 账号A,取关马督工,并重新生成备份, 账号B恢还原

![图片](https://github.com/user-attachments/assets/e903ae28-f608-4cac-9010-366c1bd1653f)

**Comment by hzhilong** [comment]
好的，感谢反馈，今天或者明天更新一版。

**Comment by hzhilong** [comment]
已修复，版本已更新；
