### ISSUE TITLE
收藏夹的改进

### ISSUE THREAD

**Issue by PastGone** [hzhilong/bilibili-backup#7]
b站限制创建100个收藏夹，所以是否可以当收藏夹创建失败时，将该收藏夹的视频移入默认收藏夹？

**Comment by hzhilong** [comment]
抱歉，刚看到。
第一次知道这个规则，我试试。

**Comment by hzhilong** [comment]
感谢。软件已更新。[bilibili-backup_2.0.8](https://github.com/hzhilong/bilibili-backup/releases/tag/v2.0.8)

![PixPin_2024-12-29_12-04-31](https://github.com/user-attachments/assets/4bed7fc0-7bdc-42ca-baba-f5159c669a82)

**Comment by PastGone** [comment]
> 感谢。软件已更新。[bilibili-backup_2.0.8](https://github.com/hzhilong/bilibili-backup/releases/tag/v2.0.8)
> 
> ![PixPin_2024-12-29_12-04-31](https://github.com/user-attachments/assets/4bed7fc0-7bdc-42ca-baba-f5159c669a82)

感谢大佬。
