### ISSUE TITLE
建议：发布中加入一个不含jre的版本

### ISSUE THREAD

**Issue by klzw2233** [hzhilong/bilibili-backup#8]
从GitHub下载速度很慢，建议去掉jre，改为使用电脑上已安装的jre

**Comment by hzhilong** [comment]
好的。已在打包时增加该版本。系统需设置JAVA_HOME环境变量才能运行。
[bilibili-backup-without-jre_2.0.8](https://github.com/hzhilong/bilibili-backup/releases/tag/v2.0.8)
